version: "3.6"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "1935:1935"

  rtmp-auth:
    build:
      context: .
      dockerfile: rtmp-auth.dockerfile
    ports:
      - "8082:8000"
    volumes:
      - auth_store:/go/rtmp-auth/store.db

volumes:
  auth_store:
