version: "3.6"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    restart: always
    depends_on:
      - rtmp-auth
    ports:
      - "1935:1935"

  rtmp-auth:
    build:
      context: .
      dockerfile: rtmp-auth.dockerfile
    restart: always
    ports:
      - "8082:8000"
    volumes:
      - auth_store:/store

volumes:
  auth_store:
